name: Java Continuous Integration and Continuous Development

on:
  push:
    branches: [ "main" ]

jobs:
  CheckOut:
    name: Checkout Source Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17 Environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Install Dependencies with Maven
        run: mvn clean install

  TestCase:
    name: Running Test Case
    runs-on: ubuntu-latest
    needs: CheckOut  # Ensures the 'test' job runs only after 'CheckOut' job completes

    steps:
      - name: Checkout Source Code for Testing
        uses: actions/checkout@v4

      - name: Set up JDK 17 Environment for Testing
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests with Maven
        run: mvn test


  BuildAndPush:
    name: Build And Push
    runs-on: ubuntu-latest
    needs: TestCase  # Ensures the 'test' job runs only after 'CheckOut' job completes

    steps:
      - uses: actions/checkout@v3
        name: Build and Push in Docker Hub

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: manzoor2930/github-action
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


