name: Java Continuous Integration and Continuous Development

on:
  push:
    branches: [ "main" ]

jobs:
  CheckOut:
    name: Checkout Source Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17 Environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Install Dependencies with Maven
        run: mvn clean install

  SonarQubeIntegration:
    name: Code Review
    runs-on: ubuntu-latest
    needs: CheckOut  # Ensures the 'SonarQubeIntegration' job runs only after 'CheckOut' job completes

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: 'fbf6d73b5293c7ec53169a9b4f3e2703a11eaeee'
          SONAR_HOST_URL: 'https://sonarcloud.io/'



  TestCase:
    name: Running Test Case
    runs-on: ubuntu-latest
    needs: SonarQubeIntegration  # Ensures the 'test' job runs only after 'CheckOut' job completes

    steps:
      - name: Checkout Source Code for Testing
        uses: actions/checkout@v4

      - name: Set up JDK 17 Environment for Testing
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests with Maven
        run: mvn test


  BuildAndPush:
    name : Build and Push
    runs-on: ubuntu-latest
    needs: TestCase
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: manzoor2930/github-cation:1.1




