name: Java Continuous Integration and Continuous Development

on:
  push:
    branches: [ "main" ]

jobs:
  CheckOut:
    name: Checkout Source Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17 Environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Install Dependencies with Maven
        run: mvn clean install

  TestCase:
    name: Running Test Case
    runs-on: ubuntu-latest
    needs: CheckOut  # Ensures the 'test' job runs only after 'CheckOut' job completes

    steps:
      - name: Checkout Source Code for Testing
        uses: actions/checkout@v4

      - name: Set up JDK 17 Environment for Testing
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests with Maven
        run: mvn test




  BuildAndPush:
    name : Build and Push
    runs-on: ubuntu-latest
    needs: TestCase
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: manzoor2930/github-cation:1.0




